In [1]:
import pandas as pd

In [19]:
df = pd.read_excel("financial_statements/15Q3-17Q2/BalanceSheet_PVD_24.xlsx")

In [20]:
# Reset and drop Indexes
df = df.iloc[6:]
df = df.iloc[:-3]   #Drop the "powered by fiintrade"
df = df.reset_index(drop=True)
# Tranpose and reset the index again
df = df.transpose().reset_index(drop=True)
# Set the first row as headers
new_headers = df.iloc[0]
df = df[1:]
df.columns = new_headers
df = df.rename(columns={"ITEMS": "Quarter"})  
# Add a new column named: "Ticker"     
# df.insert(1, "Ticker", f"{ticker}")
# df = df.iloc[::-1]

In [17]:
balancesheet_columns_to_process = ["TOTAL ASSETS", "CURRENT ASSETS", "Cash and cash equivalents", "Short-term investments", "Accounts receivable", "Inventories", "Other current assets", "LONG-TERM ASSETS", "Long-term trade receivables", "Fixed assets", "Investment properties", "Long-term incomplete assets", "Long-term investments", "Other long-term assets", "LIABILITIES", "Current liabilities", "Long-term liabilities", "OWNER'S EQUITY", "Capital and reserves", "Budget sources and other funds", "Bonus and welfare funds (Before 2010)", "Minority Interest", "TOTAL RESOURCES"]

In [21]:
df.head()

,Quarter,TOTAL ASSETS,CURRENT ASSETS,Cash and cash equivalents,Cash,Cash equivalents,Short-term investments,Short-term investments,Provision for diminution,Held-to-maturity securities,...,Undistributed earnings,Beginning accumulated undistributed earnings,Current period undistributed earnings,Minority interests,Budget sources and other funds,Bonus and welfare funds (Before 2010),Budget sources and other funds,Funds used for fixed asset acquisitions,Minority Interest,TOTAL RESOURCES
1,Q1 2015,26617488598270,9635418000300,3083289102570,1079009622920,2004279479650,9999996040,9999996040,0,0,...,4231635680009,0,4231635680009,0,0,0,0,0,272111335440,26617488598270
2,Q2 2015,26289090944820,9415466600760,3293857527840,989883423540,2303974104300,420000000000,0,0,420000000000,...,4633417461545,3873193525639,760223935906,306868339343,0,0,0,0,0,26289090944820
3,Q3 2015,26416384057500,9444978495650,3216704784950,1252556644050,1964148140900,626000000000,0,0,626000000000,...,4165522745002,2965278410639,1200244334363,308955097153,0,0,0,0,0,26416384057500
4,Q4 2015,24929213059850,8221084440100,3496561570250,2042522821400,1454038748850,889864501650,0,0,889864501650,...,4232787272993,2965278410639,1267508862354,303925641173,0,0,0,0,0,24929213059850
5,Q1 2016,24231982792500,7778923393500,2923411275960,2297051604960,626359671000,1294296302880,0,0,1294296302880,...,4248198578071,4226353331722,21845246349,292740606224,0,0,0,0,0,24231982792500

In [22]:
df2 = df[balancesheet_columns_to_process]

In [23]:
df2.head()

,TOTAL ASSETS,CURRENT ASSETS,Cash and cash equivalents,Short-term investments,Short-term investments,Accounts receivable,Inventories,Inventories,Other current assets,Other current assets,...,LIABILITIES,Current liabilities,Long-term liabilities,OWNER'S EQUITY,Capital and reserves,Budget sources and other funds,Budget sources and other funds,Bonus and welfare funds (Before 2010),Minority Interest,TOTAL RESOURCES
1,26617488598270,9635418000300,3083289102570,9999996040,9999996040,5419457730570,1053678049290,1110797160820,68993121830,253903290,...,14320486268250,7555177278910,6765308989340,12024890994580,12024890994580,0,0,0,272111335440,26617488598270
2,26289090944820,9415466600760,3293857527840,420000000000,0,4546410178620,1000409828220,1115728481340,154789066080,0,...,13411790962020,5974961915340,7436829046680,12877299982800,12877299982800,0,0,0,0,26289090944820
3,26416384057500,9444978495650,3216704784950,626000000000,0,4422259774100,1030712299450,1148932360600,149301637150,0,...,13184719498600,5746114744550,7438604754050,13231664558900,13231664558900,0,0,0,0,26416384057500
4,24929213059850,8221084440100,3496561570250,889864501650,0,2792037623400,1007217970350,1132496446200,35402774450,0,...,11618851238250,4449849544450,7169001693800,13310361821600,13310361821600,0,0,0,0,24929213059850
5,24231982792500,7778923393500,2923411275960,1294296302880,0,2616176685780,881674057740,1012693323600,63365071140,0,...,11002079838120,4216388339940,6785691498180,13229902954380,13229902954380,0,0,0,0,24231982792500